### ISSUE TITLE
geocod.io api version 1.7 is now available

### ISSUE THREAD

**Issue by Verindra** [danielbrent/geocodio-client#2]
it doesn't sound like 1.7 will break anything with 1.6, and 1.6 still functions. It also doesn't appear that there's any change to the API format, I was able to pull this project, modify the version to 1.7, and test it successfully.

**Comment by danielbrent** [comment]
I believe https://github.com/danielbrent/geocodio-client/pull/3 should resolve this, though it may be something that should be set to a configuration at a later date
